In [1]:
import numpy as np
import pandas as pd

# make DataFrame from List

In [28]:
lst1=[1,2,3]
lst2=[4,5,6]
df2=pd.DataFrame({'1':lst1,'2':lst2},index=('a','b','c'))
df1

1  2  3
a  1  2  3
b  4  5  6

In [27]:
lst1=[1,2,3]
lst2=[4,5,6]
df2=pd.DataFrame({'1':lst1,'2':lst2},index=('a','b','c'))
df2

1  2
a  1  4
b  2  5
c  3  6

# Explore in Data

In [2]:
df=pd.read_csv('googleplaystore.csv',na_values='#')
df.head()

X                                                App        Category  \
0  0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN   
1  1                                Coloring book moana  ART_AND_DESIGN   
2  2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN   
3  3                              Sketch - Draw & Paint  ART_AND_DESIGN   
4  4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN   

   Rating   Reviews  Type Last.Updated     Installs  
0     4.1     159.0  Free     1/7/2018      10,000+  
1     3.9     967.0  Free    1/15/2018     500,000+  
2     4.7   87510.0  Free     8/1/2018   5,000,000+  
3     4.5  215644.0  Free     6/8/2018  50,000,000+  
4     4.3     967.0  Free    6/20/2018     100,000+

In [135]:
df.shape

(10839, 8)

In [4]:
df.index

RangeIndex(start=0, stop=10839, step=1)

In [5]:
df.columns

Index(['X', 'App', 'Category', 'Rating', 'Reviews', 'Type', 'Last.Updated',
       'Installs'],
      dtype='object')

In [6]:
df.dtypes

X                 int64
App              object
Category         object
Rating          float64
Reviews         float64
Type             object
Last.Updated     object
Installs         object
dtype: object

In [7]:
df.describe()

X       Rating       Reviews
count  10839.000000  9366.000000  1.063900e+04
mean    5419.189962     4.191757  4.476114e+05
std     3129.379024     0.515219  2.952909e+06
min        0.000000     1.000000  0.000000e+00
25%     2709.500000     4.000000  3.700000e+01
50%     5419.000000     4.300000  2.062000e+03
75%     8128.500000     4.500000  5.404850e+04
max    10840.000000     5.000000  7.815831e+07

In [8]:
df.describe(include='all')

X     App Category       Rating       Reviews   Type  \
count   10839.000000   10839    10839  9366.000000  1.063900e+04  10439   
unique           NaN    9658       33          NaN           NaN      2   
top              NaN  ROBLOX   FAMILY          NaN           NaN   Free   
freq             NaN       9     1971          NaN           NaN   9671   
mean     5419.189962     NaN      NaN     4.191757  4.476114e+05    NaN   
std      3129.379024     NaN      NaN     0.515219  2.952909e+06    NaN   
min         0.000000     NaN      NaN     1.000000  0.000000e+00    NaN   
25%      2709.500000     NaN      NaN     4.000000  3.700000e+01    NaN   
50%      5419.000000     NaN      NaN     4.300000  2.062000e+03    NaN   
75%      8128.500000     NaN      NaN     4.500000  5.404850e+04    NaN   
max     10840.000000     NaN      NaN     5.000000  7.815831e+07    NaN   

       Last.Updated    Installs  
count         10839       10839  
unique         1377          22  
top        8/3/2018  1,000,000+  
freq            326        1579  
mean            NaN         NaN  
std             NaN         NaN  
min             NaN         NaN  
25%             NaN         NaN  
50%             NaN         NaN  
75%             NaN         NaN  
max             NaN         NaN

In [33]:
rating=df['Rating']
rating.shape

(10839,)

In [34]:
df[['Rating','Type','App']]

Rating  Type                                                App
0         4.1  Free     Photo Editor & Candy Camera & Grid & ScrapBook
1         3.9  Free                                Coloring book moana
2         4.7  Free  U Launcher Lite – FREE Live Cool Themes, Hide ...
3         4.5  Free                              Sketch - Draw & Paint
4         4.3  Free              Pixel Draw - Number Art Coloring Book
...       ...   ...                                                ...
10834     4.5  Free                                   Sya9a Maroc - FR
10835     5.0  Free                   Fr. Mike Schmitz Audio Teachings
10836     NaN   NaN                             Parkinson Exercices FR
10837     4.5  Free                      The SCP Foundation DB fr nn5n
10838     4.5  Free      iHoroscope - 2018 Daily Horoscope & Astrology

[10839 rows x 3 columns]

# Accessibility

In [35]:
df.iloc[5,3]

4.4

In [37]:
df.loc[:,'App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...                        
10834                                     Sya9a Maroc - FR
10835                     Fr. Mike Schmitz Audio Teachings
10836                               Parkinson Exercices FR
10837                        The SCP Foundation DB fr nn5n
10838        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10839, dtype: object

# number of missing value and their place

In [38]:
df.isna().sum()

X                  0
App                0
Category           0
Rating          1473
Reviews          200
Type             400
Last.Updated       0
Installs           0
dtype: int64

In [4]:
#columns with null 
null_columns = df.columns [df.isna().sum() > 0]
null_columns

Index(['Rating', 'Reviews', 'Type'], dtype='object')

In [5]:
count_null_values = {}
for i in null_columns:
    count_null_values[i] = df[i].isna().sum()

count_null_values = pd.DataFrame(list(count_null_values.items()), columns=["feature", "count"])
count_null_values

feature  count
0   Rating   1473
1  Reviews    200
2     Type    400

In [41]:
df.index[df['Rating'].isna()]

Int64Index([   23,   113,   123,   126,   129,   130,   134,   163,   180,
              185,
            ...
            10814, 10816, 10819, 10820, 10821, 10822, 10823, 10829, 10833,
            10836],
           dtype='int64', length=1473)

In [42]:
np.where(df['Rating'].isna())

(array([   23,   113,   123, ..., 10829, 10833, 10836]),)

In [44]:
np.where(df.isna())

(array([   23,    65,    67, ..., 10833, 10836, 10836]),
 array([3, 5, 5, ..., 3, 3, 5]))

# number of an item in a column and place of the item

In [65]:
np.sum(df['Type']=='Free')

9671

In [67]:
df.index[df['Type']=='Free']

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            10828, 10829, 10830, 10831, 10832, 10833, 10834, 10835, 10837,
            10838],
           dtype='int64', length=9671)

# unique

In [45]:
df['Type'].unique()

array(['Free', nan, 'Paid'], dtype=object)

In [46]:
np.unique(df['Category'])

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FAMILY',
       'FINANCE', 'FOOD_AND_DRINK', 'GAME', 'HEALTH_AND_FITNESS',
       'HOUSE_AND_HOME', 'LIBRARIES_AND_DEMO', 'LIFESTYLE',
       'MAPS_AND_NAVIGATION', 'MEDICAL', 'NEWS_AND_MAGAZINES',
       'PARENTING', 'PERSONALIZATION', 'PHOTOGRAPHY', 'PRODUCTIVITY',
       'SHOPPING', 'SOCIAL', 'SPORTS', 'TOOLS', 'TRAVEL_AND_LOCAL',
       'VIDEO_PLAYERS', 'WEATHER'], dtype=object)

# Filtering

In [47]:
np.sum(df['Rating']>4)

6800

In [48]:
df.loc[df['Rating']>4,'App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
5                               Paper flowers instructions
                               ...                        
10831                                          Chemin (fr)
10834                                     Sya9a Maroc - FR
10835                     Fr. Mike Schmitz Audio Teachings
10837                        The SCP Foundation DB fr nn5n
10838        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 6800, dtype: object

In [49]:
df.loc[df['Rating']>4.5,:]

X                                                App  \
2          2  U Launcher Lite – FREE Live Cool Themes, Hide ...   
9          9                      Kids Paint Free - Drawing Fun   
13        13                              Mandala Coloring Book   
16        16       Photo Designer - Write your name with shapes   
19        19                                       ibis Paint X   
...      ...                                                ...   
10808  10810                                  Fr Lupupa Sermons   
10818  10820                                    Fr. Daoud Lamei   
10827  10829                     Bulgarian French Dictionary Fr   
10831  10833                                        Chemin (fr)   
10835  10837                   Fr. Mike Schmitz Audio Teachings   

                  Category  Rating   Reviews  Type Last.Updated     Installs  
2           ART_AND_DESIGN     4.7   87510.0  Free     8/1/2018   5,000,000+  
9           ART_AND_DESIGN     4.7     121.0  Free     7/3/2018      10,000+  
13          ART_AND_DESIGN     4.6    4326.0  Free    6/26/2018     100,000+  
16          ART_AND_DESIGN     4.7    3632.0  Free    7/31/2018     500,000+  
19          ART_AND_DESIGN     4.6  224399.0  Free    7/30/2018  10,000,000+  
...                    ...     ...       ...   ...          ...          ...  
10808             BUSINESS     4.8      19.0  Free    6/12/2018      50,000+  
10818               FAMILY     5.0      22.0  Free    6/27/2018      10,000+  
10827  BOOKS_AND_REFERENCE     4.6     603.0  Free    6/19/2016       5,000+  
10831  BOOKS_AND_REFERENCE     4.8      44.0  Free    3/23/2014       5,000+  
10835               FAMILY     5.0       4.0  Free     7/6/2018          10+  

[1917 rows x 8 columns]

In [56]:
best_apps=df.loc[(df['Rating']>4) & (df['Reviews']>1e6 ), 'App']

In [57]:
best_games=df.loc[(df['Rating']>4) & (df['Reviews']>1e6 ) & (df['Category']=='GAME'), 'App']

In [58]:
good_apps=df.loc[(df['Rating']>4) | (df['Reviews']>1e6 ), 'App']

# rating of an unknown game

In [59]:
df.index[df['App'].str.contains('Subway')]

Int64Index([1654, 1700, 1750, 1872, 1917, 1957, 3860, 3896, 4668, 5094, 5095,
            5098, 10030],
           dtype='int64')

In [60]:
df.loc[1654,'App']

'Subway Surfers'

In [62]:
subway_surfes= df.loc[df['App']=='Subway Surfers', 'Rating']
subway_surfes

1654    4.5
1700    4.5
1750    4.5
1872    4.5
1917    4.5
3896    4.5
Name: Rating, dtype: float64

# sort data in columns

In [64]:
df['Category'].sort_values()

0       ART_AND_DESIGN
35      ART_AND_DESIGN
36      ART_AND_DESIGN
37      ART_AND_DESIGN
39      ART_AND_DESIGN
             ...      
3636           WEATHER
9490           WEATHER
3635           WEATHER
4719           WEATHER
3648           WEATHER
Name: Category, Length: 10839, dtype: object

# Drop

In [70]:
df.drop('X',axis=1, inplace=True)

In [71]:
df.drop(0,axis=0,inplace=True)

# Mapping

In [76]:
mapping={'Free':0,'Paid':1}
df['Type'].map (mapping)

1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
        ... 
10834    0.0
10835    0.0
10836    NaN
10837    0.0
10838    0.0
Name: Type, Length: 10838, dtype: float64

In [79]:
df[['Rating','Reviews']].agg([np.mean,np.std,np.sum,max,min])

Rating       Reviews
mean      4.191767  4.476534e+05
std       0.515245  2.953045e+06
sum   39255.900000  4.762137e+09
max       5.000000  7.815831e+07
min       1.000000  0.000000e+00

In [80]:
df[['Rating','Reviews']].agg({'Rating':min,'Reviews':[np.std,max]})

Rating       Reviews
max     NaN  7.815831e+07
min     1.0           NaN
std     NaN  2.953045e+06

# change type to integer

In [106]:
df['Installs']=df['Installs'].str.replace(',','').str.replace('+','')

In [107]:
index_free=df.index[df['Installs']=='Free']

In [93]:
#df.loc[index_free,'Installs']='0'

In [108]:
df=df.drop(index_free, axis=0)

In [109]:
df['Installs']=df['Installs'].astype(np.int64)

In [110]:
df['Installs'].dtypes

dtype('int64')

In [111]:
#pd.to_numeric(df['Installs'])

#  runtime & change type to datetime

In [112]:
import time

In [142]:
start=time.time()
df['Updated']=df['Last.Updated'].agg(pd.Timestamp)
end=time.time()
print(f'{end-start} seconds')

0.08264613151550293 seconds


In [132]:
start=time.time()
df['Last.Updated']=pd.to_datetime(df['Last.Updated'])
end=time.time()
print(f'{end-start} seconds')

0.1166529655456543 seconds


In [143]:
df.dtypes

X                        int64
App                     object
Category                object
Rating                 float64
Reviews                float64
Type                    object
Last.Updated    datetime64[ns]
Installs                object
Updated         datetime64[ns]
dtype: object

# Time

In [140]:
df['Last.Updated'][0]

Timestamp('2018-01-07 00:00:00')

In [141]:
df['Last.Updated'][0]-df['Last.Updated'][5]

Timedelta('287 days 00:00:00')

In [154]:
df['Last.Updated'][0].day

7

In [145]:
df['Last.Updated'][0].month

1

In [146]:
df['Last.Updated'][0].year

2018

In [147]:
df['Last.Updated'][0].dayofweek

6

In [148]:
df['Last.Updated'][0]-pd.Timestamp.now()

Timedelta('-1767 days +08:25:54.917531')

In [150]:
df['Last.Updated'][0].day_name()

'Sunday'

In [151]:
df['Last.Updated'][0].month_name()

'January'

In [152]:
df['Last.Updated'][0].date()

datetime.date(2018, 1, 7)

# how many days past from last update 

In [157]:
now=pd.Timestamp.now()
df['years']=df['Last.Updated'].agg(lambda x: np.abs((x-now)/365).days)
(df['years']>7).sum()

320

In [158]:
df.loc[df['years']>7,'Last.Updated']

58      2014-08-26
170     2014-10-16
458     2014-07-06
753     2014-08-21
768     2014-07-11
           ...    
10789   2013-12-18
10796   2012-02-06
10828   2014-01-20
10830   2014-02-16
10831   2014-03-23
Name: Last.Updated, Length: 320, dtype: datetime64[ns]

# Cancat

In [3]:
X = pd.read_csv("age.csv")
y = pd.read_csv("finish.csv")
X=pd.DataFrame(X)
y=pd.DataFrame(y)
df1=pd.concat([X,y],axis=1)
df1.head()

age        time
0   18  181.616667
1   17  182.066667
2   17  190.133333
3   17  191.600000
4   17  199.733333

# array to data frame

In [4]:
from sklearn.preprocessing import StandardScaler
stand_scaler=StandardScaler()
df1=stand_scaler.fit_transform(df1)
type(df1)

numpy.ndarray

In [5]:
df1=pd.DataFrame(df1,columns=['age','time'])
df1.head()

age      time
0 -2.134142 -1.377038
1 -2.225581 -1.369126
2 -2.225581 -1.227295
3 -2.225581 -1.201507
4 -2.225581 -1.058504