In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler,scale

In [2]:
df=pd.read_csv('Seatdata.csv')
df.head()

Stature  Sitting Height       SHS        BMI  L11  H17  Weight       SeatX
0     1740             931  0.535057  18.397410  -55  685    55.7  320.008170
1     1877             870  0.463506  22.593552   95  685    79.6  620.317771
2     1764             962  0.545351  22.881413   20  635    71.2  606.858170
3     1686             906  0.537367  29.444916  -55  685    83.7  660.937775
4     1786             933  0.522396  22.760076   95  685    72.6  615.836151

In [5]:
%whos

Variable         Type         Data/Info
---------------------------------------
MinMaxScaler     type         <class 'sklearn.preproces<...>sing._data.MinMaxScaler'>
StandardScaler   type         <class 'sklearn.preproces<...>ng._data.StandardScaler'>
df               DataFrame         Stature  Sitting Hei<...>n\n[399 rows x 8 columns]
np               module       <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd               module       <module 'pandas' from '/U<...>ages/pandas/__init__.py'>


In [6]:
X=df.iloc[:,:-1]

In [9]:
stand_scaler=StandardScaler()
minmax_scaler=MinMaxScaler()

In [10]:
X1=stand_scaler.fit_transform(X)
X1

array([[ 0.07574224,  0.64171003,  0.39948172, ..., -1.1869275 ,
         1.1810178 , -1.70356371],
       [ 1.88927614, -0.73171421, -1.68946235, ...,  1.20491125,
         1.1810178 ,  0.09831232],
       [ 0.39344161,  1.33967972,  0.70001327, ...,  0.00899188,
        -0.01498754, -0.53498302],
       ...,
       [ 1.79661382, -0.23638088, -1.29533948, ...,  1.20491125,
         1.1810178 ,  0.92008841],
       [-0.22871966, -0.84428996, -0.51349275, ...,  0.00899188,
        -0.01498754, -1.22105297],
       [ 1.2538774 ,  0.52913427, -0.44044977, ..., -1.1869275 ,
        -1.21099287, -0.36911996]])

In [11]:
X2=minmax_scaler.fit_transform(X)
X2

array([[0.51473923, 0.6123348 , 0.54808646, ..., 0.        , 1.        ,
        0.26708075],
       [0.82539683, 0.34361233, 0.19474295, ..., 1.        , 1.        ,
        0.56397516],
       [0.569161  , 0.74889868, 0.59892117, ..., 0.5       , 0.5       ,
        0.45962733],
       ...,
       [0.80952381, 0.44052863, 0.26140857, ..., 1.        , 1.        ,
        0.69937888],
       [0.46258503, 0.3215859 , 0.39365743, ..., 0.5       , 0.5       ,
        0.34658385],
       [0.71655329, 0.59030837, 0.4060126 , ..., 0.        , 0.        ,
        0.48695652]])

In [14]:
X3=scale(X)
X3

array([[ 0.07574224,  0.64171003,  0.39948172, ..., -1.1869275 ,
         1.1810178 , -1.70356371],
       [ 1.88927614, -0.73171421, -1.68946235, ...,  1.20491125,
         1.1810178 ,  0.09831232],
       [ 0.39344161,  1.33967972,  0.70001327, ...,  0.00899188,
        -0.01498754, -0.53498302],
       ...,
       [ 1.79661382, -0.23638088, -1.29533948, ...,  1.20491125,
         1.1810178 ,  0.92008841],
       [-0.22871966, -0.84428996, -0.51349275, ...,  0.00899188,
        -0.01498754, -1.22105297],
       [ 1.2538774 ,  0.52913427, -0.44044977, ..., -1.1869275 ,
        -1.21099287, -0.36911996]])

In [15]:
%whos

Variable         Type              Data/Info
--------------------------------------------
MinMaxScaler     type              <class 'sklearn.preproces<...>sing._data.MinMaxScaler'>
StandardScaler   type              <class 'sklearn.preproces<...>ng._data.StandardScaler'>
X                DataFrame              Stature  Sitting Hei<...>n\n[399 rows x 7 columns]
X1               ndarray           399x7: 2793 elems, type `float64`, 22344 bytes
X2               ndarray           399x7: 2793 elems, type `float64`, 22344 bytes
X3               ndarray           399x7: 2793 elems, type `float64`, 22344 bytes
df               DataFrame              Stature  Sitting Hei<...>n\n[399 rows x 8 columns]
minmax_scaler    MinMaxScaler      MinMaxScaler()
np               module            <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd               module            <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
scale            function          <function scale at 0x11845b9d0>
s